### ISSUE TITLE
HTTP 504 after playing video

### ISSUE THREAD

**Issue by MoeMorox** [simogeo/Filemanager#387] opened 2015-09-11 11:45 UTC
Hello,

after starting a video, then pausing it, navigating to other folders gives me a "Failed to load resource: the server responded with a status of 504 (OK): http://filemanager/connectors/php/filemanager.php?path=%2Fuserfiles%2FSerien%2F&mode=getfolder&showThumbs=true&time=341".
It seems to me like the video is still loading in the background: after a few seconds I get this: "Failed to load resource: net::ERR_CONNECTION_RESET: file.avi".
Is there some option to disable loading after stopping the video and navigating to somewhere else?

Thanks in advance!

**Comment by simogeo** [comment] 2015-09-11 11:54
It seems there is no problem in the online demo : http://fm.linea21.com/

Try with chrome_japan.ogv file ....

**Comment by MoeMorox** [comment] 2015-09-11 12:15
Yup, the online demo works perfect.
Does the online demo use the git repo too?
My videos are mounted via a samba share over a VPN, could this cause my problem?

Thanks!

**Comment by simogeo** [comment] 2015-09-11 12:59
> Does the online demo use the git repo too?

yes, there is a sync.

> My videos are mounted via a samba share over a VPN, could this cause my problem?

No idea. Why don't you try to install another FM instance and test video locally

**Comment by simogeo** [comment] 2015-09-14 12:40
I close the issue. Please let us know if you find the cause. Thanks and good luck

**Closed by simogeo** 2015-09-14 12:40 UTC
